-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Nov 18, 2021 at 05:40 AM
-- Server version: 8.0.18
-- PHP Version: 7.3.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `artif`
--
CREATE DATABASE IF NOT EXISTS `artif` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `artif`;

-- --------------------------------------------------------

--
-- Table structure for table `customer`
--

DROP TABLE IF EXISTS `customer`;
CREATE TABLE `customer` (
  `ID` int(11) NOT NULL,
  `username` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(200) COLLATE utf8mb4_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `customer`
--

INSERT INTO `customer` (`ID`, `username`, `name`, `email`, `password`) VALUES
(1, '12333', '1233', '1233', '1233');

-- --------------------------------------------------------

--
-- Table structure for table `tanaman`
--

DROP TABLE IF EXISTS `tanaman`;
CREATE TABLE `tanaman` (
  `ID` int(200) NOT NULL,
  `nama` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `jenis` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `harga` int(200) NOT NULL,
  `stok` int(200) NOT NULL,
  `deskripsi` varchar(1000) COLLATE utf8mb4_general_ci NOT NULL,
  `gambar` varchar(1000) COLLATE utf8mb4_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tanaman`
--

INSERT INTO `tanaman` (`ID`, `nama`, `jenis`, `harga`, `stok`, `deskripsi`, `gambar`) VALUES
(1, 'Fake Holiday Greens Red Holly Berry Branch - 32\"', 'Artificial Plants', 18, 916, 'This winter season, decorate your home for Christmas with realistic artificial wreaths that last. Perfect for indoor or outdoor spaces, this fake holly leaf holiday greens wreath with red waterproof berries on a grapevine base is a festive choice. 22\" Wide x 11\" Opening x .5\" Berries Base, 2\" Wide Leaves, 2.25-2.75\" Tall x 1.25-1.5\" Wide Waterproof Berries Plastic, Silk, Grapevine. Indoor/Outdoor Made in Factory that Abides by Ethical Labor Laws Assembled by Hand', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FakeIvyLeaveswithRedBerries_900x1260.jpg'),
(2, 'Outdoor Fake Red Waterproof Berry and Holly Christmas Wreath - 22\"', 'Artificial Plants', 88, 52, 'This winter season, decorate your home for Christmas with realistic artificial wreaths that last. Perfect for indoor or outdoor spaces, this fake holly leaf holiday greens wreath with red waterproof berries on a grapevine base is a festive choice. 22\" Wide x 11\" Opening x .5\" Base, 2\" Wide Leaves, 2.25-2.75\" Tall x 1.25-1.5\" Wide Waterproof Berries Plastic, Silk, Indoor/Outdoor. Made in Factory that Abides by Ethical Labor Laws Assembled by Hand ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/RedWaterproofBerryWreath_900x1260.jpg'),
(3, 'Outdoor Fake Red Waterproof Berry and Holly Christmas Garland - 4\'', 'Artificial Plants', 78, 258, 'Take the simple approach to your winter home decor with fake holiday greens and Christmas greenery garlands that last. This variegated green white artificial holly leaves garland with red waterproof berries on a grapevine base is a festive choice. 4\' Long x 8\" Wide x .5\" Berries Base, 2\" Wide Leaves, 2.25-2.75\" Tall x 1.25-1.5\" Wide Plastic, Silk, Grapevine Waterproof Berries Indoor/Outdoor. Made in Factory that Abides by Ethical Labor Laws Assembled by Hand', 'https://cdn.shopify.com/s/files/1/1334/4597/products/WaterprrofRedBerryandGrapevineGarland_720x.progressive.jpg'),
(4, 'Fake Cimicifuga Ramosa Fall Leaves in Mustard - 31\"', 'Artificial Plants', 18, 1835, 'Find fake fall leaves, like this beautiful mustard yellow Cimicifuga Ramosa leaf spray. This artificial fall foliage has a warm autumn hue that\'s sure to enhance your floral arrangements and door wreaths this season. Mustard Yellow 31\" Tall x 15\" Wide Main Stem, 10\" Tall 180 Leaves, 1-3\" Long Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSC622-YE-Yellow-Cimi-Fall-Leaves_976f24d5-ec57-40aa-8450-f78ca3f77cf9_720x.progressive.jpg'),
(5, 'Terracotta Artificial Spiral Eucalyptus Fall Leaves - 34\"', 'Artificial Plants', 13, 595, 'Find artificial leaves in warm autumn color tones, like this earthy terracotta fake spiral eucalyptus leaf spray. The perfect way to style fall flower wreaths and vase arrangements for your fall home decor. Terracotta 34\" Tall x 10\" Wide 1.25-2\" Leaves Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Fall-Leaves-Spiral-Eucalyptus_900x.progressive.jpg'),
(6, 'Fake Smoke Tree Leaves in Terra Cotta Orange - 28\"', 'Artificial Plants', 14, 2359, 'Find fake fall leaves, like this stunning Terra Cotta orange and flame cotinus smoketree leaf spray. The artificial foliage has a rich, warm hue that offers enough color to stand alone in your favorite vase for autumn decor. Terracotta Orange 28\" Tall x 1.75-3\" Leaves Coated Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A3437_900x.progressive.jpg'),
(7, 'Autumn Orange Artificial Fall Oak Leaf Branch - 38\"', 'Artificial Plants', 12, 552, 'Find artificial fall leaves, like this beautiful autumn orange fake oak leaf branch with hints of golden yellow and red. Easily style into floral and vase arrangements to ready your home for the harvest season. Autumn Orange, Red, and Green 38\" Tall 22 Leaves, 4.5-6\" Long x 3.25-4.25\" Wide Soft Plastic Coated Silk ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSO121-FA-Fall-Oak-Leaves_1296x.progressive_7bea1b7f-ef01-4070-a92b-062087f4a527_900x.progressive.jpg'),
(8, 'Fall Red Orange Artificial Japanese Maple Leaves - 27\"', 'Artificial Plants', 14, 3428, 'Find artificial fall leaves, like this gorgeous dark red burgundy fake Japanese maple leaf branch. This faux fall foliage has a rich, warm autumn hue that\'s sure to enhance your floral arrangements and door wreaths this season. Red Orange 27\" Tall 31 Leaves, 2.75- 25\"', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSM008-RE-Red-Orange-Maple-Leaves_900x.progressive.jpg'),
(9, 'Fake Foxtail Fall Grass in Beige - 36\"', 'Artificial Plants', 9, 323, 'Find artificial grasses, like this foxtail grass spray in beige. It\'s the perfect coastal decor, use fake filler grass to enhance your flower arrangements and floral wreaths. Beige 36\" Tall 3 Blooms, 8-8.5\" Tall x 1\" Wide Silk and Flocked Wired Stem, Blooms, and Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A3404_900x.progressive.jpg'),
(10, 'Fake Cedar Christmas Greenery - 28\"', 'Artificial Plants', 12, 345, 'Find artificial holiday greens for your winter floral designs, like this beautiful green cedar evergreen spray. It\'s a great addition to DIY Christmas wreaths or use as fake filler greenery in vase arrangements. Green 28\" Tall x 10\" Wide Soft Latex Leaves Plastic Berries and Wired Stem', 'https://cdn.shopify.com/s/files/1/1334/4597/products/YSC027-GR-Cedar-Branch-Natural-Looking_900x1260.jpg'),
(11, 'Red Burgundy UV Protected Outdoor Fake Coleus Hanging Plant - 25\"', 'Artificial Plants', 26, 211, 'Find indoor/outdoor artificial hanging plants, like this UV protected fake hanging coleus bush. Its rich red burgundy leaves make your planters absolutely striking. 25\" Long x 16\"  Leaves, 1.5-4.5\" Tall x .75-3.25\" Wide Main Stem, 3\" Tall UV Protected Indoor/Outdoor', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PBC533-BU-GR-Burgundy-Red-Fake-Coleus-Bush_720x.progressive.jpg'),
(12, 'Natural Touch Pothos Hanging Fake Plant - 48\"', 'Artificial Plants', 54, 100, 'This unbelievable real-touch hanging pothos is the plant you\'ve been waiting for! Replace your needy hanging plants with one that doesn\'t need sunlight or water. Why we love this: \"I no idea it was fake! It looks like you\'ve been growing it for 10 years. It\'s the perfect trailing.\". Variegated Green 48\" Long x 2-5\" Leaves Main Stem, 6\" Tall Real Touch Pot NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/35073-VG-Variegated-Real-Touch-Hanging-Pothos_720x.progressive.jpg'),
(13, 'Real Touch Hanging Pothos Fake Plant - 22\"', 'Artificial Plants', 38, 178, 'Fake plants never looked so real. Like this gorgeous green artificial pothos house plant with real-to-the-touch foliage, you can easily arrange it in a planter or hanging basket to showcase its stunning trailing leaves. Green 22\" Long x 12\" Wide x 2-4.5\" Leaves Main Stem, 5.5\" Tall Real Touch Indoor/Outdoor Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/35050-GR-Real-Touch-Green-Pothos_6f2f15ed-13d1-48fb-a324-6739768871e4_900x1260.jpg'),
(14, 'Artificial Magnolia Leaf Spray in Dark Green - 34.5\" Tall', 'Artificial Plants', 22, 1048, 'Create a gorgeous dark green artificial magnolia leaf arrangement that will always be a classic choice for your wedding designs. This fake foliage greenery looks great in floral arrangements and flower bouquets alike. Dark Green with Brown Accents 34.5\" Tall Leaves 4.75-6.5\" Long x 2-3\" Wide Plastic Wired Plastic Stem', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A4502_720x.progressive.jpg'),
(15, 'Fake Olive Branch - 35\"', 'Artificial Plants', 18, 255, 'Enjoy permanent botanicals in this ever-popular olive leaf branch with dark burgundy and green foam olives. Display these green artificial fake leaves in a tall vase to create a beautiful look. 35\" Tall x 11.5\" Wide 88 Leaves, 1.25-2.75\" Long x .25-.75\" Wide 7 Olives, .5-.75\" Long x .5-.75\" Wide Main Stem Before Foliage, 15\" Tall', 'https://cdn.shopify.com/s/files/1/1334/4597/products/15211A-Olive-Leaf-Branch_900x.progressive_4b8f2c50-065c-40a5-a86e-0ff766ad298c_900x.progressive.jpg'),
(16, 'Artificial Plants Hanging Tradescantia Houseplant - 41\" Long', 'Artificial Plants', 38, 1192, 'Find artificial hanging house plants that need no care to keep your living space bright and fresh! This fake tradescantia hanging plant with trailing leaves will look gorgeous in a basket or a planter. Item will arrive flat in packaging. Simply bend the stems and fluff! Two Tone Green 41\" Long x 10.5\" Wide 1.5-2.25\" Leaves 18 Wired Vines, 7.5-38.5\" Long Natural Touch Pot Not Included **70% Up-Cycled Plastic, 30% Environmental Plastic Made in Factory that Abides by Ethical Labor Laws Assembled by Hand', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Fake-Plants-Hanging-Tradescantia-Plant-MTF22106-GRN_900x.progressive.jpg'),
(17, 'Artificial Tropical Mimosa Leaf Branch - 41\"', 'Artificial Plants', 16, 82, 'Find artificial greenery stems to enhance your floral arrangements, like this beautiful green fake mimosa leaf branch. The wispy tropical leaves are a great way to add dimension to any design. Two Tone Green 41\" Tall x 1.75-5\" Leaves Plastic ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSM411-GR-Fake-Mimosa-Leaves_720x.progressive.jpg'),
(18, 'Artificial Pittosporum Leaf Branch - 28\"', 'Artificial Plants', 24, 97, 'Styling with artificial leaf stems is a simple and trendy approach to decorating the home. All you need is a few of these fake pittosporum leaves branches and your favorite vase to create a look that lasts. Variegated Green 28\" Tall x 7\" Wide Leaves, 2.25-3\" Tall x 1-1.5\" Wide Wax Coated Silk ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/13896A-Fake-Pittosporum-Leaf-Branch_720x.progressive.jpg'),
(19, 'Fake Eucalyptus Leaves Stem - 39\"', 'Artificial Plants', 14, 1248, 'Faux greenery to enhance your decor is found in this gorgeous green eucalyptus branch. Simply style these artificial eucalyptus leaves in a tall vase to bring the look of nature indoors. Green 39\" Tall Leaves, 4.75-6.5\" Tall x 1.5-1.75\" Wide Silk ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSE040-GR-Artificial-Eucalyptus_1296x.progressive_1296x.progressive_9bf77e1c-0f81-4c90-9845-d87a57d6ebf2_720x.progressive.jpg'),
(20, 'Artificial Seeded Eucalyptus Leaves - 23\" Tall', 'Artificial Plants', 8, 2745, 'Find fake greenery for your DIY floral arrangements, like this green artificial seeded eucalyptus foliage spray. These leaves will look lovely in any wedding flower bouquet. Green 23\" Tall x 2.5-3.5\" Leaves Silk Length of Stem Before Foliage is 10\" Long', 'https://cdn.shopify.com/s/files/1/1334/4597/products/rachelelizabethcreates_7fc4c8a9-7071-46fa-82ea-59c688a66e19_720x.progressive.jpg'),
(21, 'Artificial Seeded Eucalyptus Spray in Green Burgundy - 19\" Tall', 'Artificial Plants', 6, 7299, 'Add texture and greenery to any bouquet or centerpiece with this Seeded Eucalyptus Spray in Green Burgundy. Afloral.com offers a wide variety of artificial greenery to add beauty to your creations. Green Burgundy 19-20\" Tall 18 Leaves, 2.5\" Long Shop Seeded Eucalyptus Learn How To Make A Wreath with Artificial Eucalyptus', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSE646-Greenery-Fake-Eucalyptus_900x.progressive.jpg'),
(22, 'Real Touch Silver Dollar Eucalyptus - 30\" Tall', 'Artificial Plants', 16, 3577, 'Find popular artificial foliage and greenery for your wedding bouquet, like these gorgeous silver dollar eucalyptus leaves. Perfect to add a natural look! Green 30\" Tall Leaves, 1-2\" Tall x 1-3\" Wide Foliage Portion is 16\" Long Real Touch Made in Factory that Abides by Ethical Labor Laws Assembled by Hand', 'https://cdn.shopify.com/s/files/1/1334/4597/products/domesticblonde_2_900x.progressive.jpg'),
(23, 'Faux Real Touch Eucalyptus Branch - 31\" Tall', 'Artificial Plants', 16, 4765, 'This gorgeous green artificial eucalyptus leaf spray is absolutely beautiful greenery for your DIY wedding arrangements! Green 31\" Tall Leaves, 2-3.75\" Tall x .75-1.5\" Wide Foliage Portion, 14\" Long Real Touch', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSE029-Real-Touch-Eucalyptus-Greenery_b6cf9aef-50be-4842-9d2f-7553b4127b54_900x.progressive.jpg'),
(24, 'Artificial Real Touch Silver Dollar Eucalyptus Leaves - 26\"', 'Artificial Plants', 14, 129, 'From your everyday vase arrangements to designing floral wreaths, it\'s always a great choice to include fake eucalyptus greenery. These dusty grey green artificial silver dollar euc leaves complete the look. Dusty Gray Green 26\" Tall Leaves, 1.25-2\" Tall x 1-3\" Wide Real Touch with Plastic Stem Wired Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSE190RealTouchEucalyptus_900x1261.jpg'),
(25, 'Green Grey Artificial Spiral Eucalyptus Branch - 40\"', 'Artificial Plants', 20, 424, 'Find faux greenery to simply bring the look of nature to your home decor, like this beautiful spiral eucalyptus leaf branch in green with a gray hue. Just style these artificial leaves in a tall vase for a stunning statement piece. Green Grey 40\" Tall Silk  ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSE039-GR-GY-Green-Grey-Spiral-Eucalyptus_900x.progressive.jpg'),
(26, 'Indoor/Outdoor Artificial Eucalyptus Garland - 8\'', 'Artificial Plants', 36, 1954, 'Fall in love with artificial wedding greenery garlands like this green eucalyptus garland. Dress up this luscious euc garland with silk flowers to use as a floral table runner. Perfect to accent chairs, arches, hallways, backdrops, and more for DIY event centerpieces. Frosted Green 8\' Long x 6\" Wide Plastic Indoor/Outdoor Use Frosting is unique to each garland, color may vary. ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Eucalyptus-Garland-with-Dusting_900x.progressive.jpg'),
(27, 'Afloral Real Touch Norfolk Pine Wreath - 24\"', 'Artificial Plants', 58, 579, 'Decorate your home for the holidays with hassle-free artificial holiday greens and pine wreaths, like this awesome natural touch Norfolk pine wreath. It will stay beautiful and fresh all winter long. Green and Brown 24\" Wide 13\" Inner Diameter Grapevine, 2\" Thick Real Touch Wired Pine Branches on Heavy Grapevine Made in Factory That Abides by Labor Laws (recognized by industry standards and BSCI audits) Assembled by Hand', 'https://cdn.shopify.com/s/files/1/1334/4597/products/norfolk-pine-wreath-in-holiday-decor_900x.progressive.jpg'),
(28, 'Real Touch Faux Juniper Holiday Greens - 28\" Tall', 'Artificial Plants', 14, 3736, ' Are you looking for artificial holiday greens? Explore Afloral.com and find your favorites, like this natural touch juniper greenery with faux pine cones. It will add a festive touch to your Christmas flower arrangements and winter wedding bouquets. Green 28\" Tall x 8\" Wide Real Touch Made in Factory that Abides by Ethical Labor Laws (recognized by industry standards and BSCI audits) Assembled by Hand', 'https://cdn.shopify.com/s/files/1/1334/4597/products/MTX48397-NAGR-Fake-Green-Juniper-Branch_900x.progressive.jpg'),
(29, 'Faux Eucalyptus Garland - 6\'', 'Artificial Plants', 32, 680, 'Decorating made simple, start your table scapes with a garland and simply add florals, or add a garland to your head board or cupboards.  Green with Grey Hue Approximately 6\' Long Artificial Wedding Greenery', 'https://cdn.shopify.com/s/files/1/1334/4597/products/SLK-PGE483-GRGY-Faux-Eucalyptus-Garland-1_857x1200.jpg'),
(30, 'Artificial Baby\'s Tears Fern Leaf Branch - 36\"', 'Artificial Plants', 16, 6, 'Spruce up your home in a trendy way with stunning green artificial leaves, like this fake baby\'s tears fern. Simply style several of these branches in a tall vase and you have a table decor piece that showcases beautiful foliage. 36\" Tall x 12\" Wide Plastic ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/HSF106-GR-Baby-Tear-Fern_3022ae4d-e45c-44fc-9932-85010b9971df_900x.progressive.jpg'),
(31, 'Flocked Lambs Ear Leaf Fake Plants - 28\" Tall', 'Artificial Plants', 10, 1227, 'Greenery is a great way to fill out a wedding bouquet or centerpiece in a natural-looking way, and this flocked lamb\'s ear is no exception. Leaves are flocked for a realistic, almost velvety feel. The flocking creates a soft, grey-green look. Grey Green 28\" Tall x 8\" Wide 39 Leaves, 2-4\" Long Flocked Leaf portion is 13\" Long', 'https://cdn.shopify.com/s/files/1/1334/4597/products/QSL005-GR-Flocked-Lambs-Ear_900x.progressive.jpg'),
(32, 'Artificial Lemon Leaf Spray - 27\" Tall', 'Artificial Plants', 10, 1823, 'Get artificial greenery and leaves, like this beautiful green faux lemon leaf spray with berries. Add color and texture to your wedding bouquets and centerpieces with these lemon leaves. Green 27\" Tall 24 Leaves, 2.5-3.5\" Long x 1.5-2.25\" Wide Silk and Plastic', 'https://cdn.shopify.com/s/files/1/1334/4597/products/IMG_0599-2_900x.progressive.jpg'),
(33, 'Fake Seeded Eucalyptus Leaves in Blush - 18\" Tall', 'Artificial Plants', 6, 3029, 'Find popular artificial eucalyptus leaves in pink, like this beautiful soft blush seeded euc spray. This fake foliage is great to style into floral arrangements and flower bouquets for a touch of elegance. Blush 18\" Tall Leaves, 2-2.5\" Tall x 1\" Wide Silk Leaves Flocked Plastic Seeds', 'https://cdn.shopify.com/s/files/1/1334/4597/products/ZSE647-BS-Blush-Eucalyptus-Leaves_900x1260.jpg'),
(34, 'Fake Fall Terracotta Seeded Eucalyptus Leaves - 23\"', 'Artificial Plants', 6, 1652, 'Styling with artificial fall leaves is a simple approach to decorating your home for autumn. Give your floral wreaths and vase arrangements warm hues with these terracotta fake seeded eucalyptus leaves. Terracotta 23\" Tall x 16\" Wide Leaves, 3.75-4.25\" Long x 1.25-1.75\" Wide Silk and Plastic', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSE045-TC-Terracotta-Fall-Leaves_85aba562-90bb-4d8b-8031-fa8fc005461b_900x.progressive.jpg'),
(35, 'Fake Outdoor Plants UV Protected Artificial Geranium Leaf Hanging Plant - 21\"', 'Artificial Plants', 15, 1818, 'Find fake plants for your outdoor hanging baskets, like this gorgeous variegated green geranium leaf hanging bush that is UV protected. This luscious green geranium plant is perfect to add to your outside patio home decor! Variegated Green 21\" Long x 15\" Wide x 1.75-3.5\" Leaves Main Stem, 3.25\" Tall Silk UV Protected Indoor/Outdoor', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Geranium-Leaves-Greenery_900x.progressive.jpg'),
(36, 'Green Faux Flower Branch with Hanging Amaranthus - 37\"', 'Artificial Plants', 14, 32, 'This artificial flower branch has beautiful green hanging amaranthus flowers. Style alone in a vase for an eye-catching centerpiece, or you can incorporate the cascading faux blooms into an arrangement for dimension and texture. Green 37\" Tall x 16\" Wide Blooms, 3-5.5\" Long x .5\" Wide Flocked Blooms Silk Leaves Painted Floral Tape Wrapped Stem Fully Wired Stems Share this:', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSA038-GR-Green-Artificial-Amaranthus_900x.progressive.jpg'),
(37, 'Fake Spring Green Seeded Dogwood Foliage Branch - 36\"', 'Artificial Plants', 14, 662, 'Find artificial stems to add textural elements to your floral designs, like this branch with light green fake seeded dogwood cluster blooms and leaf foliage. Its fresh color perfectly complements spring flower arrangements. Light Green 36\" Tall x 1.5-2.5\" Bloom Clusters\r\nPlastic ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSD236-CR-GR-Green-Dogwood-Seed-Branch_900x.progressive.jpg'),
(38, 'Artificial Natural Touch Cedar Pine Pick - 10\" Tall', 'Artificial Plants', 8, 2081, 'Are you looking for artificial holiday greens? Explore Afloral.com and find your favorites, like this adorable cedar pick. It will add a festive touch to your Christmas flower arrangements and winter wedding bouquets. Green 10\" Tall x 8\" Wide Main Stem, 3.5\" Tall Natural Soft Touch Wired Branches', 'https://cdn.shopify.com/s/files/1/1334/4597/products/YKC045-GR-Wired-Cedar-Pick_900x1260.jpg'),
(39, 'Artificial Hanging Button Fern Plant in Pot - 24\" Long', 'Artificial Plants', 26, 57, 'Find artificial potted plants, like this gorgeous green fake button fern hanging plant in a plastic pot. This indoor houseplant needs no care! Green 24\" Long x 8\" Wide Black Pot; 3\" Tall x 3.5\" Wide Plastic Leaves and Pot White Planter NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/LQF569-GR-Button-Fern-Plant_900x.progressive.jpg'),
(40, 'Artificial Plants Hanging Button Leaf Plant - 40\"', 'Artificial Plants', 22, 103, 'Artificial hanging plants are the hassle-free choice to spruce up your space. Display this artificial button leaf hanging plant in a planter or a basket to showcase its lush green trailing leaves. Green 40\" Long x 9\" Wide 10 Vines, 12-37\" Long Leaves, .75-1\" Long x .25-.75\" Wide Soft Plastic Planter NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PBB331-GR-Button-Leaf-Fern_900x1260.jpg'),
(41, 'Artificial Amaranthus Spray in Green', 'Artificial Plants', 12, 382, 'Gorgeous amaranthus spray in vivid green. Also known as a summer poinsettia, this green amaranthus adds texture to hanging centerpieces and cascading wedding bouquets. Green 45\" Long 4 Vines - 12\" L, 24\" L and 26\" Total L Plastic and Foam', 'https://cdn.shopify.com/s/files/1/1334/4597/products/GTA130-GR-Hanging-Green-Amaranthus_900x.progressive.jpg'),
(42, 'Artificial Aspen Leaf Spray in Yellow Gold - 40\" Tall', 'Artificial Plants', 18, 3158, 'Beautiful artificial aspen leaf spray in festive yellow gold. Add a burst of color to your fall wedding bouquets and autumn centerpieces with these yellow gold leaves that will add stunning dimension to your DIY designs! Yellow Gold 40\" Tall x 14\" Wide 49 Leaves, 2-2.5\" Wide Silk 3 Branches Styled in 16\" Vase', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Golden-Yellow-Fake-Aspen-Leaves_898c42cd-de63-4755-8347-10b788913e44_900x.progressive.jpg'),
(43, 'Real Touch Monstera Leaf - 29\" Tall', 'Artificial Plants', 18, 11, 'Beautiful monstera leaf stem in vibrant green. Add it to your bouquets or centerpieces to give your designs an exotic, tropical feel perfect for a beach wedding or a destination wedding! 29\" Tall Leaf, 9\" Tall x 8.5\" Wide Soft Latex Wired Stem and Leaf Learn How to a Floral Balloon Arch with Tropical Flowers as seen on Green Wedding Shoes. ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/IMG_8959_900x.progressive.jpg'),
(44, 'Fake Pampas Grass in Tan - 33\"', 'Artificial Plants', 14, 384, 'Find artificial, tall grasses for trendy home decor, like this tan pampas grass stem. This fake pampas is perfect for everyday floor vase arrangements and can be easily incorporated into your fall styling. Tan 33\" Tall Plume, 12\" Tall x 4\" Wide Wired Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSG332-TN-Tan-Fake-Pampas_900x.progressive.jpg'),
(45, 'Beige Fake Palm Leaf - 37\" Tall', 'Artificial Plants', 9, 366, 'Find fake leaves to style your home decor vase arrangements, like this stunning beige palm leaf stem. These artificial palm leaves are a great neutral color that perfectly complement a design with dried grasses. Beige 37\" Tall x 6.5\" Wide Soft Plastic', 'https://cdn.shopify.com/s/files/1/1334/4597/products/PSP450-BE-Beige-Palm-Leaf_900x.progressive.jpg'),
(46, 'Artificial Bay Leaf Spray in Metallic Gold - 19\" Tall', 'Artificial Plants', 9, 3534, 'Get artificial holiday leaves, like this gorgeous metallic gold fake bay leaf spray. Use to glam up your DIY winter wedding bouquets and Christmas floral arrangements. Metallic Gold 19\" Tall x 12\" Wide 21 Leaves, 3-4\" Long x 1\" Wide Plastic', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Gold-Metallic-Bay-Leaves_900x.progressive.jpg'),
(47, 'Small Fake Snake Plant in Terracotta Pot - 14\" Tall', 'Artificial Plants', 32, 635, 'Find artificial plants for your desks and home tabletop decor, like this small, cute mother-in-law\'s tongue snake plant in a Terra Cotta pot. You can enjoy this fake potted plant for a long time and never need to worry if it has sun and water! Variegated Green 14\" Tall x 9.25\" Wide Leaves, 2-9\" Tall x 2-3.5\" Wide Terracotta Clay Planter Pot, 4.75\" Tall x 6.5\" Wide Small Size Soft Plastic & Rubber', 'https://cdn.shopify.com/s/files/1/1334/4597/products/AfloralProductPhotos-AUG2020-Resized-242_900x.progressive.jpg'),
(48, 'Faux Outdoor Snake Plant in Pot - 35\" Tall', 'Artificial Plants', 98, 302, 'Find indoor and outdoor artificial plants in pots, like this variegated green fake snake plant. This sansevieria mother-in-law\'s tongue house plant will look gorgeous on your porch or patio. Variegated Green 35\" Tall x 14\" Wide Pot, 6.75\" Tall x 8\" Wide Plastic with Preserved Moss Black Plastic Pot Included Indoor/Outdoor Use Fits 8-12\" Pot or Basket', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Afloral---Outdoor-Plants---Product-1_857x1200_59a392d2-584d-4390-9325-4aaccd8e61ac_900x.progressive.jpg'),
(49, 'Real Touch White Anemone Flower with Black Center - 14\"', 'Artificial Flowers', 6, 1186, 'Find artificial white wedding flowers, like this beautiful real touch anemone in white with a black center. This classic white anemone is an elegant addition to any flower bouquet for a soft, romantic look! White with Black Center 14\" Tall x 3\" Bloom Real Touch', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSA259-WH-White-Real-Touch-Anemone_82eb1fec-a287-45fd-997d-8ee3dbd46edc_900x.progressive.jpg'),
(50, 'Cream Magnolia Fake Flower Branch - 35\"', 'Artificial Flowers', 18, 383, 'No matter if it\'s spring or winter, magnolias always take your flower arrangements to the next level, and these cream white artificial magnolia branches fit the bill. The realistic botanical details make these faux flowers so beautiful. 35\" Tall 2 Open Blooms, 4.5-6\" Wide Velvety Flocked Stem Fully Wired Stems ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/GTM001-CR-Cream-Silk-Magnolia_900x.progressive.jpg'),
(51, 'Green Cream Artificial Hypericum Berries - 22.5\"', 'Artificial Flowers', 9, 59, 'Find fake berries to add visual interest to your floral designs, like this beautiful hypericum berry spray in green cream. Artificial berry accents are perfect to add texture to vase decor, wreaths, and flower bouquets. 22.5\" Tall Foam Berries, .25-.5\" Wide Silk Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSB038-GR-Green-Fake-Hypericum-Berries_900x.progressive.jpg'),
(52, 'Burgundy Fake Berries Pick - 9\"', 'Artificial Flowers', 6, 2280, 'From vase arrangements to DIY wreaths to wedding flower bouquets, artificial berries give your floral designs extra texture and visual interest. This beautiful burgundy fake, mini berry pick is the perfect addition, especially for fall or winter decor. 9\" Tall x 5.5\" Wide .25-.5\" Foam and Plastic Mini Size', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Burgundy-Fake-Berry-Pick_900x.progressive.jpg'),
(53, 'Cream Artificial Berries Branch - 24\"', 'Artificial Flowers', 12, 587, 'Find fake berries to style your holiday floral arrangements, like this super elegant cream artificial berry branch accented with green leaves. Such a simple way to DIY festive Christmas wreaths and winter wedding flower bouquets. 24\" Tall x .5\" Berries Plastic Coated Foam Berries Silk Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/XBS132-WH-Cream-Fake-Berry-Stem_900x1260.jpg'),
(54, 'Artificial Winter Red Berry Pick - 14\"', 'Artificial Flowers', 8, 977, 'Find fake berry picks in your favorite Christmas colors! These festive red and burgundy artificial berries accented with green leaves are just what you need for holiday flower arrangements and winter floral wreaths. 14\" Tall x .5\" Berries Foam Coated Berries Silk Leaves ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/XBK239-RE-Red-Fake-Berries_900x.progressive.jpg'),
(55, 'White Real Touch Tulip Flower Bundle of 12 - 14.5\"', 'Artificial Flowers', 32, 893, 'Find fake flower bundles, like this beautiful bundle of white mini real touch tulip flowers. Simply drop in your vase for an everlasting spring arrangement, or take apart to use the life-like tulips in multiple designs. White 14.5\" Tall 12 Blooms, 2\" Tall x 1.25\" Wide Real Touch Blooms and Leaves Plastic Stems Tied with Raffia, Easy to Separate', 'https://cdn.shopify.com/s/files/1/1334/4597/products/11399B-WH-White-Real-Touch-Tulips_900x.progressive.jpg'),
(56, 'Real Touch Flower White Tulips Bundle of 5 - 22\" Tall', 'Artificial Flowers', 26, 516, 'Bring a forever spring feeling to your home with this beautiful white artificial flower bundle of real touch tulips. Just drop in your favorite vase and these life-like tulip flowers instantly cheer up any room! White 22\" Tall 5 Blooms, 2-2.5\" Tall x 1.15-1.5\" Wide Real Touch Tied with Raffia, Easy to Separate', 'https://cdn.shopify.com/s/files/1/1334/4597/products/15452B-WH-White-Tulips-Bundle_900x.progressive.jpg'),
(57, 'Vanilla Ivory Fake Peony Fall Flower - 22\"', 'Artificial Flowers', 12, 1469, 'Artificial flowers in neutrals are found in this lovely peony stem in a mix of ivory and vanilla. Style these fake peonies into your fall floral arrangements to create a dramatic contrast between subtle and bold hues. Vanilla Ivory 22\" Tall Bloom, 2.5\" Tall x 4.5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP266-VA-Vanilla-Cream-Fake-Peony_900x.progressive.jpg'),
(58, 'Fake Peony Fall Flower in Purple Green - 22\"', 'Artificial Flowers', 12, 639, 'Find silk flowers for fall home decor, like this peony artificial flower stem in purple and green. It\'s a beautiful color combination to complement your fall floral designs for the autumn season. Purple and Green 22\" Tall Bloom, 2.5\" Tall x 4.5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP266-PU-Artificial-Peony-in-Green-Purple_900x.progressive.jpg'),
(59, 'Artificial Snowy Peony Flower in Pink Blush', 'Artificial Flowers', 12, 1126, 'Beautiful pink blush faux peony flowers stem is sprinkled with a white dusting that gives it a snowed look. Style this snowy peony into Christmas wreaths and holiday floral arrangements for a soft, elegant look. Pink Blush with Snowed Look 27.5\" Tall x 4.5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/XFS278-SNPK-Snowy-Pink-Peony_900x1260.jpg'),
(60, 'Silk English Cabbage Rose in Mauve Pink - 25\" Tall', 'Artificial Flowers', 10, 169, 'Find artificial flowers for your DIY fall wedding floral arrangements, like this absolutely beautiful mauve pink fake English cabbage rose stem. It will be the focal point of your bridal flower bouquet. Mauve Pink 25\" Tall x 3.5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR258-MV-Silk-Flowers-Mauve-Open-Rose_720x.progressive.jpg'),
(61, 'Natural Touch Peony Stem in Cream White - 30\" Tall', 'Artificial Flowers', 18, 232, 'This real touch cream peony adds elegance to any arrangement. Have the beauty of fresh, but without the hassle! Perfect to create enchanting DIY bouquets and centerpieces. Cream White 30\" Tall x 5.5\" Bloom Real Touch', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP104-CR-Real-Touch-Peony_900x.progressive.jpg'),
(62, 'Indoor/Outdoor Water Resistant Artificial Poinsettia Bush in Red', 'Artificial Flowers', 8, 1302, 'Water resistant poinsettia bush in red. This poinsettia bush is perfect for your outdoor holiday decor. Use alone or in an arrangement with other assorted holiday flowers and greenery. Red 15\" Tall 7 Blooms, 5\" Wide Silk Water Resistant Indoor/Outdoor Vase NOT Included ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Red-Poinsettia-XPO210-RE-2_720x.progressive.jpg'),
(63, 'Beige Faux Dried Roses with Bud - 21\"', 'Artificial Flowers', 12, 742, 'These beautiful beige fake roses are the perfect silk flowers for your fall wedding centerpieces. Easily style the artificial blooms into a flower bouquet. After autumn ends, these neutral color stems fit perfectly in any everyday arrangement. 21\" Tall x 1.25-2.5\" Blooms Silk with Dried Look and Feel', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR527-BE-Beige-Fake-Roses_900x.progressive.jpg'),
(64, 'Burgundy Faux Dried Roses with Bud - 21\"', 'Artificial Flowers', 12, 905, 'Find faux flowers in rich fall colors, like this striking burgundy silk rose spray. These burgundy fake roses upgrade your autumn decor vase arrangements and fall wedding centerpieces alike. 21\" Tall x 1.25-2.5\" Blooms Silk with Dried Look and Feel', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR527-BU-Burgundy-Fake-Roses_900x.progressive.jpg'),
(65, 'Pink Faux Cherry Blossom Flower Branch - 40\"', 'Artificial Flowers', 18, 8519, 'Find artificial spring flowering branches, like this pretty pink fake cherry blossom flower branch. These pink cherry blossoms are sure to complete your wedding flower bouquet.  Overall Size, 40\" Tall x 18\" Wide Flowering Portion is 12-15\" Flower Size, 1.25-2\" Wide Blooms', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSB079PK-Pink-Fake-Cherry-Blossom_900x1260.jpg'),
(66, 'Artificial Spring Cherry Blossoms in Cream - 40\"', 'Artificial Flowers', 18, 3190, 'Build your spring wedding flowers bouquet with these beautiful cream artificial cherry blossom flower branches. Then, use as a home vase arrangement to enjoy year after year.  Cream 40\" Tall x 18\" Wide 1.25-2\" Wide Blooms Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSB079-CR-White-Cherry-Blossom-Branch_900x.progressive.jpg'),
(67, 'Cream Artificial Magnolia Leaf and Flower Wreath - 22\"', 'Artificial Flowers', 38, 167, 'From front door decor to home wall decor, artificial flower wreaths are sure to beautify your space. This lovely wreath has cream fake magnolia flowers and lush green leaves perfect for spring. 22\" Wide', 'https://cdn.shopify.com/s/files/1/1334/4597/products/White-Fake-Magnolia-Wreath_900x.progressive.jpg'),
(68, 'Artificial Real Touch Magnolia Flower and Bud Branch in White - 31\"', 'Artificial Flowers', 29, 302, 'Find artificial spring flowers that are always in bloom, like this high-quality flowering branch with a white faux magnolia flower and lush green leaves. Simply style in your ginger jar to create an effortlessly gorgeous look. White Dark Green Leaves with Rust Brown Undersides\r\n31\" Tall x 7\" Bloom 13 Leaves, 4.5-6.75\" Long x 2-3.25\" Wide Real Touch Shiny Leaves Flocked Bud\r\n', 'https://cdn.shopify.com/s/files/1/1334/4597/products/CC323-Real-Touch-Magnolia_857x1200.jpg'),
(69, 'Blue Purple Fake Bearded Iris Flower - 28\"', 'Artificial Flowers', 12, 141, 'Find artificial spring flowers that you can enjoy any time of the year, like this gorgeous bearded iris silk flower in purple and blue. Its water-resistant stem allows you to create a vase arrangement that has a fresh-cut look. 28\" Tall Bloom, 5.5\" Tall x 4.5\" Wide Water-Resistant Stem Wired Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSI320-PU-Indigo-Iris_900x.progressive.jpg'),
(70, 'Artificial Wild Raspberry Berries in Plum - 27\"', 'Artificial Flowers', 14, 219, 'Beautiful faux wild raspberry spray in two-tone plum with Marsala tones. Add these rich plum purple wild berries to wedding designs and centerpieces for a complementary accent to your decor! Two Tone Plum 27\" Tall Nine,  1\" Wide Berries Foam Berries Main Stem is 12.5\" Tall', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSB183-PL-Artificial-Wild-Raspberries_900x.progressive.jpg'),
(71, 'Purple Foxglove Artificial Flower - 26\"', 'Artificial Flowers', 20, 123, 'Find fake flowers for your everyday vase arrangements, like this gorgeous purple silk foxglove stem. Offering the perfect pop of color, these artificial foxgloves are beautiful blooms for spring and summer alike. 26\" Tall 21 Blooms, 1-2\" Long x .5-1.5\" Wide Main Stem, 15\" Long Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/GA1496-PU-Foxglove-in-Purple-Pink_900x.progressive.jpg'),
(72, 'Ranunculus Fake Flower in Yellow - 18.75\"', 'Artificial Flowers', 7, 214, 'Find artificial flowers that offer bright, cheerful color, like this adorable yellow silk ranunculus stem with a bud. Simply style a few of these fake blooms in a bud vase, place on your side table, and enjoy! 18.75\" Tall x 3\" Bloom Stem is Not Wired', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR277-YE-Ranunculus-in-Yellow_900x.progressive.jpg'),
(73, 'Red Fake Poppy Flower', 'Artificial Flowers', 9, 431, 'Find nature-inspired artificial flowers, like this gorgeous red silk poppy flower spray. From bud vase table arrangements to wildflower bouquets, these colorful fake poppies have that pop you\'re looking for. 23\" Tall x 2-2.5\" Blooms Flocked Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP304-RE-Red-Silk-Poppy_900x.progressive.jpg'),
(74, 'Yellow Faux Dill Wildflowers - 35\"', 'Artificial Flowers', 12, 17, 'Find nature-inspired artificial flowers, like this whimsical wildflower dill spray in yellow. Simply style these fake wildflowers in a vase to create that fresh-cut look you can enjoy every day. 35\" Tall 3 Flower Heads, 2.75-5.5\" Wide .5-1.25\" Individual Blooms Main Stem, 19.5\" Long Flocked Plastic and Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSD330-YE-Yellow-Fake-Dill-Flowers_900x.progressive.jpg'),
(75, 'Artificial Wildflowers Lupinus in Blue - 33\"', 'Artificial Flowers', 12, 48, 'Looking for artificial wildflowers like lupinus? Shop now to find these fake lupine flowers in striking blue and green with purple highlights. The water-resistant stem makes it easy to create a fresh-cut inspired arrangement. 33\" Tall Bloom, 9\" Tall x 2.5\" Wide Water-Resistant Stem', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSL040-BL-Blue-Fake-Lupinus_900x.progressive.jpg'),
(76, 'Bright Orange Fake Freesia Flowers - 27\"', 'Artificial Flowers', 8, 6, 'Find fake flowers that are colorful and brighten your floral arrangements, like this gorgeous orange silk freesia flower stem. The artificial blooms sweeten any summer wedding flower bouquet. 27\" Tall 2 Open Blooms, 3\" Wide  ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSF016-OR-Orange-Freesia_900x.progressive.jpg'),
(77, 'Cream White Ranunculus Silk Flower - 18.75\"', 'Artificial Flowers', 7, 752, 'Beautiful cream white silk ranunculus flowers stem with a bud. This artificial ranunculus flower offers that classic, timeless look to complete your vase arrangements or wedding flower bouquets. 18.75\" Tall x 3\" Bloom Stem is Not Wired ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR277-WH-Cream-White-Ranunculus_900x1260.jpg'),
(78, 'Oversized Artificial Hydrangea in Blush - 9\" Bloom', 'Artificial Flowers', 14, 593, 'Make a statement with oversized artificial flowers, like this lovely soft blush pink hydrangea stem with a jumbo silk bloom. You just need to style it in your favorite bud vase to complete a fresh, trendy look. 19\" Tall Oversized Bloom, 5\" Tall x 9\" Wide', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSH233-BS-Blush-Pink-Hydrangea_900x1260.jpg'),
(79, 'Pink Mauve Faux Dried Roses with Bud - 21\"', 'Artificial Flowers', 12, 1699, 'Find pink artificial flowers, like this pretty pink mauve silk rose spray. Whether you style these faux roses in vase arrangements or flower bouquets, they lend classic elegance to any floral design. 21\" Tall x 1.25-2.5\" Blooms Silk with Dried Look and Feel', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR527-MV-Pink-Mauve-Faux-Roses_900x1260.jpg'),
(80, 'Oversized Artificial Coral Pink Hydrangea - 9\" Bloom', 'Artificial Flowers', 14, 311, 'Find fake oversized flowers to create trendy bud vase arrangements, like this stunning coral pink silk hydrangea stem with a jumbo bloom. Its bright pop of color is sure to make your living room side table the focal point. 19\" Tall Oversized Bloom, 5\" Tall x 9\" Wide', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSH233-CO-Coral-Fake-Hydrangea_720x.progressive.jpg'),
(81, 'Variegated Pink Faux Clematis Flower Branch - 46\"', 'Artificial Flowers', 16, 81, 'Offering striking height, elegance, and a pop of color, this artificial clematis wildflower branch is going to be your favorite for styling tall vases. It has pretty pink faux flowers in variegated coloring with white accents. Variegated Pink with White 46\" Tall 3 Blooms, 3.5-4.5\" Wide Soft Flocked Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSC243-BT-Pink-Faux-Climbing-Clematis_900x.progressive.jpg'),
(82, 'Peach Fake Ranunculus Flowers - 25\"', 'Artificial Flowers', 8, 668, 'A beautiful way to bring a refreshing splash of color to your floral vase arrangements or flower bouquets starts with this artificial ranunculus stem. The perfect peach hue with apricot tones makes these silk flowers a favorite. 25\" Tall 2 Buds and 1 Bloom, 1-3.5\" Wide Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR401-PE-Peach-Silk-Ranunculus_edd99514-7c41-44b4-a46f-bdc169d1bf61_900x1260.jpg'),
(83, 'Pastel Pink Yellow Ranunculus Fake Flowers - 25\"', 'Artificial Flowers', 8, 500, 'Find fake flowers in pretty pastels, like this silk ranunculus stem in light pink with light yellow highlights. The color gradient is perfectly refreshing, making these artificial blooms a favorite to cheer up your everyday vase arrangements. 25\" Tall 2 Buds and 1 Bloom, 1-3.5\" Wide Wired Stems ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR401-PK-YE-Light-Pink-Ranunculus_900x1260.jpg'),
(84, 'Coral Pink Fake Flower Bundle of Mini Ranunculus - 11\"', 'Artificial Flowers', 12, 954, 'Fake flower bundle of gorgeous coral pink mini silk ranunculus blooms offers versatility for home decorating and weddings alike. Simply drop in a vase or take apart and use the artificial flowers in bouquets. 11\" Tall x 7\" Wide 1-2\" Wide Blooms 6 Stems Tied with Raffia,  to Separate Mini Size', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR125-CO-Coral-Pink-Mini-Ranunculus_900x.progressive.jpg'),
(85, 'Artificial Peony Flower in Peach - 19\" Tall', 'Artificial Flowers', 8, 249, 'Find high-quality artificial peonies, like this pretty peach peony silk flowers stem. For a beautiful look that lasts, you can easily bundle some stems together, drop in a vase, and display on a nightstand or a table. 19\" Tall x 6\" Bloom', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP501-PE-Peach-Silk-Peony_900x.progressive.jpg'),
(86, 'Coral Artificial Peony Flower - 19\" Tall', 'Artificial Flowers', 8, 300, 'Find high-quality fake flowers, like this gorgeous peony silk flower stem in coral. Simply bundle several artificial peonies together, drop in a vase, and you have an arrangement that brings instant cheer. 19\" Tall x 6\" Bloom', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP501-CO-Coral-Silk-Peony_900x.progressive.jpg'),
(87, 'Dahlia Silk Flower Stem in Soft Yellow Peach - 19\"', 'Artificial Flowers', 7, 247, 'Offering perfect pastel color, this lovely soft yellow peach faux dahlia flower belongs in any spring floral arrangement. You can easily DIY a bundle of artificial dahlias and drop in a vase, or style a few stems in a flower bouquet. Soft Yellow Peach 19\" Tall x 5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSD411-PE-Yellow-Peach-Silk-Dahlia_95551150-ee61-443b-beb4-d66d4e226225_900x.progressive.jpg'),
(88, 'Pink Artificial Hypericum Berries - 22.5\"', 'Artificial Flowers', 9, 295, 'Find artificial berries to add visual interest to your floral designs, like this beautiful hypericum berry spray in pink with cream green accents. Perfect for adding texture to vase decor, wreaths, and flower bouquets. Pink and Cream Green 22.5\" Tall Foam Berries, .25-.5\" Wide Silk Leaves ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSB038-PK-Hypericum-Berries-in-Pink_900x.progressive.jpg'),
(89, 'Light Green Artificial Scabiosa Flowers - 24\"', 'Artificial Flowers', 12, 255, 'Find artificial flowers that offer appealing visual elements for your floral designs, like this beautiful light green scabiosa spray. The faux scabiosa pods are great to add texture to use as filler in wildflower arrangements. Light Green 24\" Tall 3 Blooms,1.5-1.75\" Wide', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSS024-GR-Light-Green-Fake-Scabiosa_900x1260.jpg'),
(90, 'Fake Flower Freesia in Violet Purple - 27\"', 'Artificial Flowers', 8, 146, 'Find artificial flowers that are colorful and brighten your floral arrangements, like this pretty violet purple faux freesia flower stem. The blooms are sure to sweeten your wedding flower bouquets. Violet Purple 27\" Tall 2 Open Blooms, 3\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSF016-PU-Silk-Flowers-Purple-Freesia_900x.progressive.jpg'),
(91, 'Faux Dill Wildflowers in Pink - 35\"', 'Artificial Flowers', 12, 424, 'Pretty pink artificial dill flower spray offers wildflowers that are sure to elevate your spring floral designs. Simply style in a bud vase for a fresh-cut look that lasts, or use to add whimsy to a flower bouquet. Pink 35\" Tall 3 Flower Heads, 2.75-5.5\" Wide .5-1.25\" Individual Blooms Main Stem, 19.5\" Long Flocked Plastic Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSD330-PK-Pink-Artificial-Dill-Flower_900x.progressive.jpg'),
(92, 'Navy Blue Artificial Berry Branch - 24\"', 'Artificial Flowers', 12, 997, 'Find artificial berry and leaf stems to enhance the look of your floral arrangements, like this fake berries branch in rich navy blue. The beautiful blueberries make Christmas wreaths and winter wedding centerpieces unique. 24\" Tall x .5\" Berries Plastic Coated Foam Berries Silk Leaves ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/XBS132-BL-NY-Navy-Blue-Fake-Berries_900x.progressive.jpg'),
(93, 'Artificial Flowers Rose Bush in Cream White - 19\"', 'Artificial Flowers', 14, 1219, 'Find artificial flower bushes to easily create beautiful designs. This cream white silk rose bush can be dropped in a vase for a simple holiday table arrangement, or clip apart to incorporate the fake roses into bouquets or corsages. 19\" Tall 10 Blooms, 3\" Wide Main Stem, 5\" Tall ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/XFB120-WH-White-Silk-Rose-Bush_900x1260.jpg'),
(94, 'Burgundy Artificial Flowers Rose Bush - 19\"', 'Artificial Flowers', 14, 781, 'This gorgeous burgundy artificial rose flowers bush is just what you need for fall floral styling. Simply drop it in a vase for an easy but stunning centerpiece, or clip apart to add the fake roses to wedding flower bouquets. 19\" Tall 10 Blooms, 3\" Wide Main Stem, 5\" Tall ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/XFB120-BU-Burgundy-Roses-Fake-Flower-Bush_900x.progressive.jpg'),
(95, 'Pink Artificial Japanese Magnolia Flower Branch - 21\"', 'Artificial Flowers', 9, 46, 'Find artificial spring flowers for your home decorating or wedding centerpieces, like this lovely pink Japanese magnolia branch. Simply bundle the faux magnolias and style in a vase for a cheerful look that lasts. Wired stems, very easy to work with! Pink 21\" Tall 2 Open Blooms, 2.25-4\" Wide Flocked Buds ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSM424-PK-Pink-Magnolia-Branch_900x.progressive.jpg'),
(96, 'Pink Carnation Artificial Flower - 17\"', 'Artificial Flowers', 6, 463, 'Find pink faux flowers, like this pretty pink silk carnation stem. From DIY floral projects to flower wreaths to vase arrangements, these artificial carnations give your designs a sweet look. 17\" Tall x 3.5\" Bloom Latex Leaves and Stem', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSC458-PK-Pink-Silk-Carnation_900x.progressive.jpg'),
(97, 'Pink Artificial Hyacinth Spring Flowers - 12.5\"', 'Artificial Flowers', 14, 22, 'Find fake spring flowers that you can enjoy any time of the year, like this bright and pretty silk hyacinth flower stem in pink with cream accents. Simply style in a side table vase for the perfect pop of color. Pink and Cream 12.5\" Tall Bloom, 5\" Tall x 2.5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/HSH337-PK-Pink-Hyacinth-Flower_720x.progressive.jpg'),
(98, 'Orange Faux Ranunculus Flowers - 25\"', 'Artificial Flowers', 8, 711, 'Find colorful artificial flowers to spice up any vase arrangement or flower bouquet, like this gorgeous orange silk ranunculus stem. The faux blooms offer a vibrant hue that\'s sure to enhance your spring and summer floral designs. Orange 25\" Tall 2 Buds and 1 Bloom, 1-3.5\" Wide Silk Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR401-OR-Orange-Ranunculus-Flower_1296x.progressive_27c0a8cd-5e57-47d7-810a-51a01d96999f_900x.progressive.jpg'),
(99, 'Lavender Artificial Lilac Flower - 25\"', 'Artificial Flowers', 22, 591, 'Ready your home for spring with high-quality silk blooms, like this stunning lavender purple lilac flowers spray. The delicate detail and distinct texture allow these artificial lilacs to elevate any flower bouquet or centerpiece. Lavender Purple 25\" Tall x 1\" Blooms Bloom Clusters, 3-5\" Tall Silk and Plastic Fully Wired Blooms and Wired Stems Styled with 5 Lilacs in Clear Vase', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSL035-LV-Lavender-Silk-Lilac_61a1e36e-f211-44d3-883b-b75e9f0f6418_900x1260.jpg');
INSERT INTO `tanaman` (`ID`, `nama`, `jenis`, `harga`, `stok`, `deskripsi`, `gambar`) VALUES
(100, 'Cream Blush Artificial Clover Wildflowers - 21.5\"', 'Artificial Flowers', 8, 693, 'Find artificial wild flowers, like this beautiful cream blush faux clover flower spray. Resembling amaranth and thistle, these clovers are a lovely choice to give your floral arrangements and bouquets extra texture. Cream and Soft Blush Pink 21.5\" Tall 3 Blooms, 1.5-2.25\" Wide Wax Coated Silk Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSC909-Cream-Clover-Flowers_900x.progressive.jpg'),
(101, 'Artificial Garden Rose in Earthy Brown - 26\"', 'Artificial Flowers', 12, 608, 'Find faux flowers in earth tones, like this beautiful garden rose stem in earthy brown with terracotta undertones. It\'s a rich color that\'s sure to make your neutral-inspired flower bouquets extra striking. Earthy Brown with Terracotta Undertones 26\" Tall Bloom, 2.75\" Tall x 4.5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/GA1490-RU-Brown-Fake-Rose_720x.progressive.jpg'),
(102, 'Azalea Silk Flowers Bush in Cream White - 12\"', 'Artificial Flowers', 16, 790, 'Find artificial flowers for your indoor or outdoor decorating, like this cream white faux azalea flower bush. Great for window boxes, or style in a table pot for a fresh look. Color may fade in direct sunlight. Add a UV Protectant Spray to keep color vibrant. Cream White 12\" Tall x 12\" Wide 12 Blooms, 1.5-3\" Wide Main Stem, 3.5\" Tall Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FBA420-WH-Cream-White-Azalea-Bush_900x.progressive.jpg'),
(103, 'Pink Azalea Silk Flowers Bush - 13\"', 'Artificial Flowers', 10, 1416, 'Find indoor/outdoor artificial flowers, like this pretty pink silk azalea flower bush. Simply style it in your favorite planter pot to brighten any space. Color may fade in direct sunlight. Add a UV Protectant Spray to keep color vibrant. Pink 13\" Tall x 10\" Wide 7 Blooms and 4 Buds, 1.75-3\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FBA507-PK-Pink-Azalea-Bush_900x.progressive.jpg'),
(104, 'Yellow Faux Spring Flowers Forsythia Branch - 36\"', 'Artificial Flowers', 10, 2856, 'Bright and beautiful yellow artificial forsythia flowering branch is ready to cheer up your home now! Simply style these faux spring flowers in a tall vase to create an effortlessly gorgeous table centerpiece. Yellow 36\" Tall x 14\" Wide Blooms, 1.5-2.25\" Wide Silk Styled with 5 Branches in White Vase', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSF416-YE-Yellow-Silk-Forsythia_900x.progressive.jpg'),
(105, 'Yellow Artificial Dancing Orchid Flowers - 40\"', 'Artificial Flowers', 20, 342, 'Find faux tropical flowers, like this beautiful yellow dancing orchid spray. Simply display the artificial orchids in a vase to create a bright and colorful arrangement for your table decor. Yellow 40\" Tall 77 Blooms, 1-1.5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/GO9072-YE-Dancing-Fake-Orchid-Yellow_900x.progressive.jpg'),
(106, 'Real Touch Austin English Rose in Peach Blush - 24\"', 'Artificial Flowers', 16, 652, 'Life-like, high-quality faux flowers are found in this lovely peach blush real touch Austin English rose. Style a few stems in your favorite bud vase and you have a simple but elegant side table arrangement. Peach Blush 24\" Tall Bloom, 2.5\" Tall x 3.5\" Wide Real Touch', 'https://cdn.shopify.com/s/files/1/1334/4597/products/RealTouchPinkOpenRose_720x.progressive.jpg'),
(107, 'Real Touch Open Dutchess Rose in Cream Blush - 20\" Tall', 'Artificial Flowers', 22, 224, 'Life-like, high-quality artificial flowers are found in this classically beautiful cream blush real touch Dutchess rose. Display a few stems in your favorite table vase for an effortlessly chic yet elegant floral arrangement. Cream Blush 20\" Tall Bloom, 2.25\" Tall x 5\" Wide Real Touch Petals and Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Blush-Peach-Real-Touch-Rose_900x.progressive.jpg'),
(108, 'White Mini Daisy Fake Wildflowers - 26\"', 'Artificial Flowers', 18, 454, 'Adorable, mini white artificial daisy flowers offer you the option to fill your everyday floral vase arrangements with wildflowers that last. Style them into any design to create the fresh feeling of spring. White 26\" Tall 30 Mini Blooms, .75\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Silk-Mini-Daisy-Flowers-in-White_900x.progressive.jpg'),
(109, 'Faux Wildflowers Viburnum Branch in Pink - 37\"', 'Artificial Flowers', 14, 394, 'Find fake wildflowers, like this pretty pink viburnum flowers branch. Its forever fresh look is certain to elevate artificial floral arrangements that keep your home bright and beautiful. Pink 37\" Tall 5 Clusters, 2.5\" Tall x 4\" Wide Blooms, 1.5\" Wide Silk Blooms with Plastic Centers', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSV370-PK-Pink-Fake-Viburnum_900x.progressive.jpg'),
(110, 'Cream Artificial Viburnum Wildflowers Branch - 37\"', 'Artificial Flowers', 14, 330, 'Looking for artificial wild flowers? Stop your search here at Afloral.com and find this beautiful fake flower branch with cream viburnum wildflowers. Its neutral color fits perfectly in any floral vase arrangement you design. Cream 37\" Tall 5 Clusters, 2.5\" Tall x 4\" Wide Blooms, 1.5\" Wide Silk Blooms with Plastic Centers', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSV370-CR-Cream-Fake-Viburnum_900x.progressive.jpg'),
(111, 'Mauve Artificial Peony Fall Flower', 'Artificial Flowers', 12, 1423, 'Find faux flowers for fall home decor, like this lovely mauve peony stem. The warm hue of these artificial peonies is certain to enhance the look of your DIY wreaths and floral centerpieces for the autumn season. Mauve with Green Accents 24\" Tall Bloom, 6\" Wide x 3.5\" Tall Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP267-MV-Mauve-Large-Peony-Flower_900x.progressive.jpg'),
(112, 'Artificial Peony Fall Flower in Ivory', 'Artificial Flowers', 14, 100, 'Timeless, elegant artificial flowers are found in this ivory silk peony flower stem. The neutral color perfectly complements bold, rich hues that look absolutely striking in your fall floral centerpieces. Ivory 24\" Tall Bloom, 6\" Wide x 3.5\" Tall Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP267-IV-Large-Ivory-Peony-Bloom_720x.progressive.jpg'),
(113, 'Red Orange Artificial Fall Peony Flower - 22\"', 'Artificial Flowers', 12, 749, 'Looking for burnt orange fake flowers? You\'ve come to the right place! Enhance your fall floral arrangements, home decor wreaths, and wedding centerpieces with this gorgeous autumn burnt red orange artificial peony flower. Red Orange 22\" Tall Bloom, 2.5\" Tall x 4.5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP266-PU-Fall-Orange-Peony_900x.progressive.jpg'),
(114, 'Fake Rose in Burnt Orange', 'Artificial Flowers', 8, 722, 'Find faux flowers for fall home decor, like this gorgeous burnt orange rose stem. These artificial roses give your fall floral wreaths and vase arrangements that warm, rich autumn hue you love. Burnt Orange 21\" Tall Bloom, 4.5\" Wide x 3\" Tall Silk with Plastic Thorns ', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR136-FL-Flame-Orange-Rose_900x.progressive.jpg'),
(115, 'Fake Artichoke Stem in Purple - 26.5\"', 'Artificial Flowers', 16, 96, 'Find trendy faux artichokes, like this artichoke stem in purple and green. This artificial artichoke makes a stunning focal point when styled in your flower arrangements and floral wreaths for fall home decor. Purple Green 26.5\" Tall Large Bloom, 5\" Tall x 5\" Wide Small Bloom, 3\" Tall x 3\" Wide', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A5379_857x1200.jpg'),
(116, 'Artificial Peony in Beige', 'Artificial Flowers', 9, 1681, 'Beautiful beige fake peony flowers stem is a great neutral hue that perfectly complements any color scheme. Its contrast to bold, rich hues in your fall floral arrangements is especially stunning. Beige 28.5\" Tall 1 Bloom, 4\" Wide 1 Bud, 2.25\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP029-BE-Beige-Fake-Peony_900x.progressive.jpg'),
(117, 'Fake Berries Pick in Cream Beige - 9\"', 'Artificial Flowers', 6, 4541, 'Find artificial Christmas picks, like this adorable cream berry pick. These fake mini berries are great to add texture to any floral arrangement, or use them in your DIY holiday wreaths for extra detail. Cream Beige 9\" Tall x 5.5\" Wide .25-.5\" Berries Foam and Plastic Mini Size', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A3022_720x.progressive.jpg'),
(118, 'UV Protected Indoor/Outdoor Fake Geranium Bush - 24\"', 'Artificial Flowers', 34, 159, 'Fake outdoor flowers are found in this stunning red artificial UV protected geranium flower bush. It\'s the perfect pop of color for your porch planters, hanging baskets, and window boxes. Red 24\" Tall x 15\" Wide Flower Clusters, 3-5\" Wide Main Stem, 6.25\" Tall Silk UV Protected Indoor/Outdoor Planter NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FBG041-Red-Indoor-Outdoor-Geranium-Bush_900x.progressive.jpg'),
(119, 'Artificial Cherry Blossom in Pastel Pink - 44\"', 'Artificial Flowers', 28, 2485, 'Keep the fresh feeling of spring all year with beautiful pink faux cherry blossom flower branches. Add these blooms to your floral arrangements, or simply bundle several stems together and display in your favorite vase. Pastel Pink 44\" Tall x 1-2.25\" Blooms Silk 12-21\" Flowering Portion Shown Styled with 2 Branches', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSB655-PK-Pink-Cherry-Blossom_900x.progressive.jpg'),
(120, 'Artificial Orange Branch - 35\"', 'Artificial Flowers', 28, 922, 'Find fake fruits, like this colorful artificial fruit branch with oranges and green leaves. Easily style it in your favorite pot or vase, or add it to a table floral arrangement for an instant bright look. Orange and Green 35\" Tall x 10\" Wide 7 Oranges, 1.25-1.5\" Wide Plastic and Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/IMG_8953_900x.progressive.jpg'),
(121, 'White Fake Waxflower Filler Flowers', 'Artificial Flowers', 6, 481, 'Beautiful white artificial waxflower spray offers the perfect, little filler flowers. From DIY vase arrangements to wedding flower bouquets to floral crowns, these white fake waxflowers add textural detail. White 26\" Tall x 6\" Wide x .5-.75\" Blooms 8 Flower Clusters, 1.5-2\" Wide Silk and Plastic Wired Stem', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSW330-WH-White-Waxflowers-Fake-Florals_720x.progressive.jpg'),
(122, 'Large White Real Touch Fake Orchids - 44\"', 'Artificial Flowers', 26, 760, 'Find tropical faux flowers, like this classically beautiful large white artificial phalaenopsis orchid spray. These realistic soft touch orchids are sure to lend a sophisticated look to your wedding flower bouquets. White with Soft Yellow Centers 44\" Tall x 4.5\" Blooms 12 Blooms Real Touch 20\" Flowering Portion', 'https://cdn.shopify.com/s/files/1/1334/4597/products/95160-WW-Large-White-Phalaenopsis-Orchid_900x.progressive.jpg'),
(123, 'Blush Pink Silk Rose Spray', 'Artificial Flowers', 9, 202, 'Give your wedding flowers or DIY centerpiece a romantic touch with this blush pink rose. Simply tuck this realistic rose spray into a flower bouquet or clip the stem and drop into a single bud vase for an elegant home decor accent. Blush Pink 21.5\" Tall 2 Open Blooms, 1 Bud: 1-3.75\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A6567.progressive_640c6777-b9df-4b48-b605-0b46c9746b08_900x.progressive.jpg'),
(124, 'Pink Mauve Silk Rose Flower', 'Artificial Flowers', 8, 1298, 'Find artificial flowers for your wedding flower bouquets and centerpieces, like this beautiful pink mauve fake rose stem. It\'s a great way to give your DIY arrangements a soft, delicate look. Pink Mauve 21.5\" Tall x 3.5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Soft-Pink-Rose-729_900x.progressive.jpg'),
(125, 'Pink Fake Flower Bundle of Mini Ranunculus - 11\"', 'Artificial Flowers', 12, 594, 'Artificial flower bundle of pretty pink mini ranunculus blooms is the perfect addition to your DIY floral designs. Drop in a vase, or take apart to use the pink silk flowers for wedding boutonnieres or bouquets. Pink 11\" Tall x 7\" Wide 1-2\" Wide Blooms 6 Stems Tied with Raffia, Easily Separated Silk Mini Size', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSR125-PK-Pink-Ranunculus-Bundle_900x.progressive.jpg'),
(126, 'Artificial Globe Thistle Flowers in Blue Grey', 'Artificial Flowers', 8, 54, 'Fill your flower arrangements and wedding floral bouquets with beautiful filler flowers, like these blue gray fake globe thistles. Artificial thistle wildflowers add the perfect texture. Blue Grey 19.5\" Tall x 6.5\" Wide 11 Blooms, 1\" Wide Bloom Portion is 6.75\" Tall Plastic Thistles, Silk Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FST169-BL-GY-Blue-Fake-Thistle_900x.progressive.jpg'),
(127, 'Silk Flowers Rose in Plum Purple', 'Artificial Flowers', 8, 2301, 'Add a touch of romance to your artificial flower bouquet with this silk rose spray in eggplant plum purple. With remarkably realistic petals and leaves, this fake flower looks anything but! Plum Purple 21.5\" Tall x 3.5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/IMG_9104_900x.progressive.jpg'),
(128, 'Artificial Flowers Rose in Taupe Beige - 21.5\" Tall', 'Artificial Flowers', 8, 1433, 'Find artificial fall flowers, like this elegant taupe beige rose stem. These fake roses will add classic beauty to your DIY fall wedding flower bouquet. Taupe Beige 21.5\" Tall x 3.5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/IMG_9313_900x.progressive.jpg'),
(129, 'Artificial Flowers Rose in Eggshell Cream - 21.5\" Tall', 'Artificial Flowers', 8, 1573, 'Classic artificial rose in eggshell cream complements both fall and winter floral designs. Add these elegant fake roses to your fall wedding flowers bouquet or holiday arrangements. Eggshell Cream 21.5\" Tall x 3.5 Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/IMG_9317_900x.progressive.jpg'),
(130, 'Artificial Indoor/Outdoor Bromeliad Plant in Orange Flame - 21\"', 'Artificial Flowers', 36, 9, 'Get artificial tropical flowers, like this orange and flame red Hawaiian bromeliad plant. Give your destination wedding centerpieces an exotic look! Orange Flame with Green Leaves 21\" Tall x 22\" Wide Bloom - 9-11\" Long x 7\" Wide Leaves - 7-15\" Long x 2\" Wide Wired, Plastic Flower and Leaves Indoor/Outdoor Use Pot NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Afloral---Outdoor-Plants---Product-29_900x.progressive.jpg'),
(131, 'Silk Peony in Light Pink - 24\" Tall', 'Artificial Flowers', 9, 1824, 'Find beautiful artificial wedding flowers, like this soft pink silk peony with a bud. A pretty pastel color for your DIY spring flower bouquets! Light Pink 24\" Tall Bloom, 3.25\" Tall x 5\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP230-Pink-Silk-Peony-Flower_720x.progressive.jpg'),
(132, 'Yellow Black-Eyed-Susan Rudbeckia Flowers - 33\"', 'Artificial Flowers', 12, 202, 'Get yellow artificial flowers, like beautiful yellow black eyed susan coneflowers. Add this silk rudbeckia to spring arrangements and summer wedding bouquets. Yellow 33\" Tall x 3-4\" Blooms Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/GA935-YE-Yellow-Black-Eyed-Susan-Flower_900x1260.jpg'),
(133, 'Fake Lilacs Flower in Cream - 25\"', 'Artificial Flowers', 22, 814, 'Find artificial spring wedding flowers, like this beautiful cream silk lilac spray. These delicate lilacs add distinct texture to fill out any bouquet or centerpiece. Cream and Green 25\" Tall x 1\" Blooms Bloom Clusters; 3-5\" Tall Silk and Plastic Wired Stems', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSL035-CR-Cream-Silk-Lilac-Stem_900x.progressive.jpg'),
(134, 'UV Protected Indoor/Outdoor Geranium Bush in Cream White - 18\"', 'Artificial Flowers', 24, 1266, 'Find artificial outdoor flowers, like this beautiful white silk geranium bush that is UV protected. Perfect for your patio hanging baskets and window boxes. Cream White\r\n18\" Tall x 12\" Wide 8 Bloom Clusters, 2.5-5\" Wide Main Stem, 3\" Tall Silk UV Protected\r\nIndoor/Outdoor Planter NOT Included Shown Styled in Planter with 2 Bushes\r\n', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FBG040-WH-White-Geranium-Bush_720x.progressive.jpg'),
(135, 'UV Protected Indoor/Outdoor Artificial Geranium Bush - 18\" Tall', 'Artificial Flowers', 24, 1666, 'Find artificial outdoor flowers, like this gorgeous red silk geranium bush that is UV protected. Perfect for your patio hanging baskets and window boxes. Red 18\" Tall x 12\" Wide 8 Bloom Clusters, 2.5-5\" Wide Main Stem, 3\" Tall Silk UV Protected Indoor/Outdoor Shown Styled with 2-6 Geranium Bushes Planter NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FBG040-RE-Red-Outdoor-Geranium-Bush_900x.progressive.jpg'),
(136, 'UV Protected Indoor/Outdoor Geranium Bush in Pink - 18\"', 'Artificial Flowers', 24, 1754, 'Find artificial outdoor flowers, like this beautiful pink silk geranium bush that is UV protected. Perfect for your patio hanging baskets and window boxes. Pink 18\" Tall x 12\" Wide 8 Bloom Clusters, 2.5-5\" Wide Main Stem, 3\" Tall Silk UV Protected Indoor/Outdoor Planter NOT Included', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FBG040-PK-Pink-Outdoor-Geranium-Bush_900x.progressive.jpg'),
(137, 'Silk Open Peony in Antique Blue - 22\" Tall', 'Artificial Flowers', 9, 1406, 'Find blue artificial wedding flowers, like this beautiful antique blue silk open peony with green highlights. Perfect for your DIY spring flower bouquets or corsages. Antique Blue 22\" Tall Bloom, 2.5\" Tall x 4\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP779-BL-Fake-Blue-Peony-Flower_900x.progressive.jpg'),
(138, 'Artificial Cosmos Flowers in Pink - 3-4\" Blooms', 'Artificial Flowers', 10, 219, 'Find artificial filler flowers at Afloral.com, like these pretty pink silk cosmos. Perfect color for your spring wedding bouquets and DIY spring wreaths. Pink 36\" Tall 6 Blooms, 3-4\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/Pink-Silk-Cosmos-Flowers.progressive_4be9373b-f69c-4628-869c-eab7779da1da_900x.progressive.jpg'),
(139, 'Cream Peach Artificial Open Peony Flower - 22\" Tall', 'Artificial Flowers', 8, 1541, 'Looking for artificial fall wedding flowers? Find many outstanding options at Afloral.com, including this open peony silk flower in peach with pink and green accents. It will look so beautiful in your DIY bridal bouquet. Cream Peach 22\" Tall Bloom, 2.25\" Tall x 4\" Wide Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSP780-CA-Silk-Cream-Peach-Peony_720x.progressive.jpg'),
(140, 'Periwinkle Blue Artificial Thistle Wildflowers', 'Artificial Flowers', 9, 499, 'If you are going to make your own artificial fall wedding bouquet, be sure to include faux filler flowers for that extra detail. These stunning navy blue wildflower thistles will do the trick! Perwinkle Blue 26-30.5\" Tall x 1.25-2\" Tall Thistles Plastic Thistle Flocked Stem and Leaves', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FST420-BL-Blue-Fake-Thistle_b62d7519-bb46-4abf-8528-3d51f71274a7_857x1200.jpg'),
(141, 'Dahlia Silk Flower in Taupe - 19.5\"', 'Artificial Flowers', 12, 611, 'Add everlasting elegance to your artificial flower arrangement with this affordable dahlia silk flower! Create a bridal bouquet or display in a tall bud vase for a simple, yet stunning home decor accent.  Taupe 19.5\" Tall x 4.5\" Bloom 1 Open Bloom and 1 Bud Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSD302-BE-Beige-Silk-Dahlia_x1200.progressive_70855f58-3f40-48e7-b4fc-1ab8fbee589a_900x.progressive.jpg'),
(142, 'Blush Peach Dahlia Silk Flower - 19\"', 'Artificial Flowers', 7, 254, 'Find blush peach artificial wedding flowers for your DIY centerpieces, like these gorgeous silk dahlias. Blush Peach 19\" Tall x 5\" Bloom Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSD411-PK-SO-Soft-Pink-Dahlia_900x.progressive.jpg'),
(143, 'Artificial Cornflower Flower in Blue', 'Artificial Flowers', 8, 2279, 'Find artificial spring flowers, like these beautiful blue fake cornflowers. These stunning blue wildflowers will make any floral arrangement pop! Blue 24\" Tall 3 Open Blooms, 1.5-2\" Wide 1 Bud Silk', 'https://cdn.shopify.com/s/files/1/1334/4597/products/FSC304-BL-Silk-Blue-Cornflower_1140x1596_5038d8af-192b-4fe2-8a90-65fc9a0006b9_720x.progressive.jpg'),
(144, 'Veronica Artificial Flower in Lavender', 'Artificial Flowers', 9, 19, 'This soft lavender artificial veronica flower spray is the perfect addition to your summer wedding flower arrangements. Lavender 30\" Tall Bloom, 9\" Tall x 1.25\" Wide Silk and Plastic 18\" Flowering Portion', 'https://cdn.shopify.com/s/files/1/1334/4597/products/3A4A3207_900x.progressive.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `customer`
--
ALTER TABLE `customer`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `tanaman`
--
ALTER TABLE `tanaman`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `customer`
--
ALTER TABLE `customer`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tanaman`
--
ALTER TABLE `tanaman`
  MODIFY `ID` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=147;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
